@url=http://localhost:5112/api/movies

### POST create movie
POST {{url}}
Content-Type: application/json

{
  "Title": "Lucian the Greek2",
  "YearOfRelease": 2024,
  "Genres": [
    "Comedy"
  ]
}

### Get by slug
@slug=lucian-the-greek2-2024
GET {{url}}/{{slug}}


### GET all movies
GET {{url}}
Accept: application/json

### Get by Id
@id = d5488162-2bd5-4e0b-8a5f-2f73d928ff30
GET {{url}}/{{id}}
Accept: application/json

### Update movie
PUT {{url}}/{{id}}
Content-Type: application/json

{
  "Title": "Lucian the Greek",
  "YearOfRelease": 2025,
  "Genres": [
    "Action"
  ]
}

### Delete movie
DELETE {{url}}/{{id}}
