@url=https://localhost:7094/api/movies

### POST create movie
POST {{url}}
Content-Type: application/json

{
  "Title": "Lucian the Greek",
  "YearOfRelease": 2023,
  "Genres": [
    "Comedy"
  ]
}

### Get by slug
@slug=nick-the-greek-2022
GET {{url}}/{{slug}}


### GET all movies
GET {{url}}
Accept: application/json

### Get by Id
@id = 7a4dc447-fb68-4bcf-92df-6d3826698724
GET {{url}}/{{id}}
Accept: application/json

### Update movie
PUT {{url}}/{{id}}
Content-Type: application/json

{
  "Title": "Lucian the Greek",
  "YearOfRelease": 2025,
  "Genres": [
    "Action"
  ]
}

### Delete movie
DELETE {{url}}/{{id}}
