@url=http://localhost:5112/api/ratings
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiMTNmZjMyNi05YTNmLTRkOTktYmJhNy1kNGFlMTNkYzdhNjAiLCJzdWIiOiJsdWNpYW4uZHVuY2FAZ21haWwuY29tIiwiZW1haWwiOiJsdWNpYW4uZHVuY2FAZ21haWwuY29tIiwidXNlcmlkIjoiZGYwMmUzZDgtYjdjYy00M2E0LWI2MjItOGQ1YTZjOGIxYjlmIiwiYWRtaW4iOmZhbHNlLCJ0cnVzdGVkX21lbWJlciI6dHJ1ZSwibmJmIjoxNzQwODYxMTU4LCJleHAiOjE3NDA4ODk5NTgsImlhdCI6MTc0MDg2MTE1OCwiaXNzIjoiaHR0cHM6Ly9pZC5kdW5jYS5jb20iLCJhdWQiOiJodHRwczovL21vdmllcy5kdW5jYS5jb20ifQ.Ddw5nYdOPGn2tLjdN_chWzJqx8StRIUxF1MymOA9_vg

### POST create rating for movie
GET {{url}}/me
Accept: application/json
Authorization: Bearer {{token}}
