@url=http://localhost:5112/api/ratings
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI0YzQ4Mzg3Yy0yNjkxLTQ3YmMtYjZhNy0wNGU5NDg5ZGVkMzYiLCJzdWIiOiJsdWNpYW4uZHVuY2FAZ21haWwuY29tIiwiZW1haWwiOiJsdWNpYW4uZHVuY2FAZ21haWwuY29tIiwidXNlcmlkIjoiZGYwMmUzZDgtYjdjYy00M2E0LWI2MjItOGQ1YTZjOGIxYjlmIiwiYWRtaW4iOmZhbHNlLCJ0cnVzdGVkX21lbWJlciI6dHJ1ZSwibmJmIjoxNzQwODM0NzAzLCJleHAiOjE3NDA4NjM1MDMsImlhdCI6MTc0MDgzNDcwMywiaXNzIjoiaHR0cHM6Ly9pZC5kdW5jYS5jb20iLCJhdWQiOiJodHRwczovL21vdmllcy5kdW5jYS5jb20ifQ.40y0_549ugGyCOU97nwsFlLX4MyuqjvGWkwoVhrTV0c

### POST create rating for movie
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "movieId": "",
  "rating": 4
}
